# Generated by Django 6.0.2 on 2026-03-02 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conv', models.CharField(choices=[('prive', 'Privé'), ('groupe', 'Groupe')], max_length=10)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
                'db_table': 'Discussion',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('discussion', models.OneToOneField(db_column='idDiscussion', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.conversation')),
                ('nom', models.CharField(max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='group_profiles/')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'Groupe',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('typeMessage', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(db_column='idDiscussion', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('expediteur', models.ForeignKey(db_column='idExpediteur', on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFichier', models.CharField(max_length=150)),
                ('urlFichier', models.FileField(upload_to='chat_documents/')),
                ('taille', models.BigIntegerField()),
                ('format', models.CharField(max_length=20)),
                ('message', models.ForeignKey(db_column='idMessage', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.message')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='MessageStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('lu', 'Lu')], max_length=10)),
                ('dateStatut', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(db_column='idMessage', on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='chat.message')),
                ('user', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, related_name='message_statuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statut de Message',
                'verbose_name_plural': 'Statuts de Message',
                'db_table': 'MessageStatut',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('membre', 'Membre')], default='membre', max_length=10)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(db_column='idDiscussion', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conversation')),
                ('user', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, related_name='discussions_participated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'Participant',
                'unique_together': {('discussion', 'user')},
            },
        ),
    ]
