# Generated by Django 6.0.2 on 2026-03-02 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatut', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('video', 'Vidéo')], db_column='type', max_length=10)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
                ('dateExpiration', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
                'db_table': 'Statut',
            },
        ),
    ]
